#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -x

: ${DB_DRIVER:=postgres}

SKIP_SCHEMA_INIT="${IS_RESUME:-false}"
VERBOSE_MODE="--verbose"
HIVE_HOME="/opt/hive"

function initialize_hive {
  COMMAND="-initSchema"
  if [ "$(echo "$HIVE_VER" | cut -d '.' -f1)" -lt "4" ]; then
     COMMAND="-${SCHEMA_COMMAND:-initSchema}"
  fi
  $HIVE_HOME/bin/schematool -dbType $DB_DRIVER $COMMAND #$VERBOSE_MODE
  if [ $? -eq 0 ]; then
    echo "Initialized schema successfully.."
  else
    echo "Schema initialization failed!"
    exit 1
  fi
}

export HIVE_CONF_DIR=$HIVE_HOME/conf
if [ -d "${HIVE_CUSTOM_CONF_DIR:-}" ]; then
  find "${HIVE_CUSTOM_CONF_DIR}" -type f -exec \
    ln -sfn {} "${HIVE_CONF_DIR}"/ \;
  export HADOOP_CONF_DIR=$HIVE_CONF_DIR
fi

# Initialize Hive schema
export HADOOP_CLIENT_OPTS="$HADOOP_CLIENT_OPTS -Xmx1G $SERVICE_OPTS"
if [[ "${SKIP_SCHEMA_INIT}" == "false" ]]; then
  # handles schema initialization
  initialize_hive
fi

# Make hive dir writable
chmod 777 /tmp/hive

chown -R root:root /etc/security/keytabs

ls -lah /etc/security

ls -lah /etc/security/keytabs

# Debugger
export HADOOP_CLIENT_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug=true"

cat /etc/hosts

# Start the metastore
export METASTORE_PORT=${METASTORE_PORT:-9083}

# Install sudo and some other tools needed to install kerberos tools.
apt-get update && apt-get install -y sudo wget curl lsof
# Install kerberos tools.
sudo apt-get install -y --no-install-recommends krb5-config krb5-user

# Remove the krb5.conf that has been generated by the installation.
sudo rm /etc/krb5.conf
# Make a copy and rename of the mounted krb5.conf.
sudo cp /etc/krb5.conf.orig /etc/krb5.conf

if kinit -kt /etc/security/keytabs/hive.hive-metastore.keytab hive/hive-metastore@EXAMPLE.COM; then
    echo "Kerberos authentication successful"
else
    echo "Kerberos authentication failed" >&2
    exit 1
fi

klist

export HADOOP_PROXY_USER=hive/hive-metastore@EXAMPLE.COM

exec $HIVE_HOME/bin/hive --skiphadoopversion --skiphbasecp $VERBOSE_MODE --service metastore # --hiveconf hive.root.logger=DEBUG,console

